UserManagement: User Management
CreateUser: Create User
DeleteUser: Delete User

ReportViewing: Report Viewing
DownloadReport: Download Report

AccessDashboard: Access Dashboard

app:
  # 通过权限的 name 或其它唯一标识符来指定角色应拥有的权限.
  permissions:
    - pname:
      name: ${UserManagement}
      permission: user:*
      description: Manage user accounts and information
    - pname: ${UserManagement}
      name: ${CreateUser}
      permission: user:create
      description: Create a new user account
    - pname: ${UserManagement}
      name: ${DeleteUser}
      permission: user:delete
      description: Delete an existing user account
    - pname:
      name: ${ReportViewing}
      permission: report:*
      description: Access and view reports
    - pname: ${ReportViewing}
      name: ${DownloadReport}
      permission: report:download
      description: Download report files
    - pname:
      name: ${AccessDashboard}
      permission: dashboard:access
      description: Access the application dashboard
  roles:
    - name: SYSTEM_ADMINISTRATOR
      permissions:
        - ${UserManagement}
        - ${CreateUser}
        - ${DeleteUser}
        - ${ReportViewing}
        - ${DownloadReport}
        - ${AccessDashboard}
    - name: GUEST
      permissions:
        - ${AccessDashboard}