server:
  port: 80

logging:
  config: classpath:log4j2-dev.xml
  level:
    indi.ly.crush: trace
#    root: debug

spring:
  application:
    name: universal_tools
  web:
    resources:
      static-locations: >
                          classpath:/MY-RESOURCES/,
                          classpath:/META-INF/resources/,
                          classpath:/resources/,
                          classpath:/static/,
                          classpath:/public/
  datasource:
    username: root
    password: crush
    url: >
            jdbc:mysql://localhost:3306/shiro_backend?
            useSSL=true&
            useUnicode=true&
            characterEncoding=UTF-8&
            useTimezone=true&
            serverTimezone=GMT%2B8&
            allowMultiQueries=true&
            rewriteBatchedStatements=true
  jpa:
    # 是否在启动时初始化数据库表.
    generate-ddl: true